export const allPackagesData = [
  {
    id: 1,
    name: "BASIC PACKAGE",
    price: "$900",
    list: [
      "Custom Logo Design Concepts: 10",
      "Dedicated Brand Designers: 2",
      "Dedicated Brand Designers: 2",
      "Custom Logo Design Concepts: 10",
      "Dedicated Brand Designers: 2",
      "Custom Logo Design Concepts: 10",
      "Dedicated Brand Designers: 2",
    ],
  },
  {
    id: 2,
    name: "PRO PACKAGE",
    price: "$1350",
    list: [
      "Custom Logo Design Concepts: 10",
      "Dedicated Brand Designers: 2",
      "Dedicated Brand Designers: 2",
      "Custom Logo Design Concepts: 10",
      "Dedicated Brand Designers: 2",
      "Custom Logo Design Concepts: 10",
      "Dedicated Brand Designers: 2",
    ],
  },
  {
    id: 3,
    name: "PREMIUM PACKAGE",
    price: "$1650",
    list: [
      "Custom Logo Design Concepts: 10",
      "Dedicated Brand Designers: 2",
      "Dedicated Brand Designers: 2",
      "Custom Logo Design Concepts: 10",
      "Dedicated Brand Designers: 2",
      "Custom Logo Design Concepts: 10",
      "Dedicated Brand Designers: 2",
    ],
  },
];

export const logoPackagesData = [
  {
    id: 1,
    name: "LOGO SPECIAL",
    price: "$45.00",
    list: [
      "4 Original Logo Concepts",
      "Dedicated Logo Designer",
      "4 Revisions",
      "With Grey Scale Format",
      "Free Icon Design",
      "Formats: Jpeg Only",
      "24 - 48 Hours Turn Around Time",
      "100% Satisfaction",
      "100% Ownership Rights",
      "Money-Back Guarantee",
    ],
  },
  {
    id: 2,
    name: "LOGO PLUS",
    price: "$89.00",
    list: [
      "Unlimited Original Logo Concepts",
      "Dedicated Logo Designer (Industry Specific)",
      "Unlimited Revisions",
      "Stationery Design (Business Card, Letterhead, Envelope)",
      "Email Signature Design",
      "Social Media Designs (Facebook, Twitter, Instagram)",
      "With Grey Scale Format",
      "Free Icon Design",
      "Formats: Jpeg, Psd, Eps, Ai, Png, Tiff, Svg",
      "24 - 48 Hours Turn Around Time",
      "100% Satisfaction",
      "100% Ownership Rights",
      "Money-Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
  {
    id: 3,
    name: "LOGO PLATINUM",
    price: "$149.00",
    list: [
      "Unlimited Original Logo Concepts",
      "Dedicated Logo Designer (Industry Specific)",
      "Unlimited Revisions",
      "Stationery Design (Business Card, Letterhead, Envelope)",
      "Email Signature Design",
      "Social Media Designs (Facebook, Twitter, Instagram)",
      "With Grey Scale Format",
      "Free Icon Design",
      "Formats: Jpeg, Psd, Eps, Ai, Png, Tiff, Svg",
      "24 - 48 Hours Turn Around Time",
      "100% Satisfaction",
      "100% Ownership Rights",
      "Money-Back Guarantee",
      "Dedicated Account Manager",
    ],
  },
];

export const illustrationPackagesData = [
  {
    id: 1,
    name: "BASIC ILLUSTRATIVE",
    price: "$294.00",
    list: [
      "3 Custom Design Concepts",
      "By 2 Designers",
      "UNLIMITED Revisions",
      "48 to 72 hours TAT",
      "All Final Files Format (AI, PSD, EPS, PNG, GIF, JPG, PDF)",
      "Ownership Rights",
      "Satisfaction Guarantee",
      "Unique Design Guarantee",
      "100% Money Back Guarantee",
    ],
  },
  {
    id: 2,
    name: "STARTUP ILLUSTRATIVE",
    price: "$394.00",
    list: [
      "4 Custom Design Concepts",
      "By 3 Designers",
      "48 to 72 hours TAT",
      "UNLIMITED Revisions",
      "All Final Files Format (AI, PSD, EPS, PNG, GIF, JPG, PDF)",
      "Ownership Rights",
      "Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee",
    ],
  },
  {
    id: 3,
    name: "PROFESSIONAL ILLUSTRATIVE",
    price: "$594.00",
    list: [
      "UNLIMITED Design Concepts",
      "By 4 Designers",
      "UNLIMITED Revisions",
      "24 to 48 hours TAT",
      "Ownership Rights",
      "100% Unique Design Guarantee",
      "100% Money Back Guarantee",
    ],
  },
];

export const informativeWebPackagesData = [
  {
    id: 1,
    name: "BASIC WEBSITE",
    price: "$399.00",
    list: [
      "Informative Website",
      "Industry Specific Designer",
      "Custom Designed Homepage (2x concept)",
      "3-5 Custom Designed Inner Pages",
      "3 Premium Stock Photos",
      "3 Unique Custom Banner Design",
      "Social Media Integration",
      "Cross Browser Compatibility",
      "Cross-Browser (Chrome, Firefox, Safari, etc.) Compatibility",
      "Search Engine Submission",
      "Google Friendly Sitemap",
      "Complete W3C Certified HTML",
      "CMS [WordPress]",
      "Unlimited Revisions",
      "After Sales Support",
      "Best Value For Money",
      "Responsive Website",
      "100% Satisfaction Guarantee",
      "100% Unique Design",
      "100% Ownership Rights",
    ],
  },
  {
    id: 2,
    name: "Standard WEBSITE",
    price: "$799.00",
    list: [
      "Informative Website",
      "Industry Specific Designer",
      "Custom Designed Homepage (2x concepts)",
      "8-10 Custom Designed inner pages",
      "CMS / Admin Panel Support",
      "6 Premium Stock Photos",
      "Search Engine Submission",
      "5 Unique Custom Banner Design",
      "1 JQuery Slider Banner",
      "Google Friendly Sitemap",
      "Cross-Browser (Chrome, Firefox, Safari, etc.) Compatibility.",
      "Social Media Integration (Facebook, Twitter, LinkedIn)",
      "Facebook + Instagram Page Creations",
      "Complete W3C Certified HTML",
      "Unlimited Revisions",
      "After Sales Support",
      "Best Value For Money",
      "Complete Deployment",
      "30 Days Free (Post-Launch Support)",
      "Dedicated Account Manager",
      "24/7 Customer Support",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Ownership Rights",
    ],
  },
  {
    id: 3,
    name: "Enterprise WEBSITE",
    price: "$1,399.00",
    list: [
      "Informative Website",
      "Industry Specific Designer",
      "Custom Designed Homepage (4x Concepts)",
      "Up To 10-15 Custom Designed Inner Pages",
      "Interactive and Dynamic Website Design",
      "Cross platform (Desktop, iPhone, Android, etc) Responsive Compatibility",
      "Online Reservation/Appointment Tool (Optional)",
      "Online Payment Integration (Optional)",
      "Custom Dynamic Forms",
      "Search Engine Submission",
      "Lead Capturing Forms (Optional)",
      "Striking Hover Effects",
      "Signup Area (For Newsletters, Offers etc.)",
      "Newsfeed Integration",
      "Social Media Integration (Facebook, Twitter, LinkedIn)",
      "Google Friendly Sitemap",
      "Search Engine Submission",
      "10 Premium Stock Photos",
      "8 Unique Custom Banner Design",
      "Interactive jQuery Slider Banner",
      "Complete W3C Certified HTML",
      "Parallax Scrolling",
      "Facebook Page Design",
      "Twitter Page Design",
      "Complete Deployment",
      "60 Days Free (Post-Launch Support)",
      "How-to-use Training Manual for CMS",
      "Dedicated Account Manager",
      "24/7 Customer Support",
      "Unlimited Revisions",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
      "100% Ownership Rights",
    ],
  },
];

export const eCommercePackagesData = [
  {
    id: 1,
    name: "BASIC WEBSITE",
    price: "$399.00",
    list: [
      "Custom designed Homepage (2x concepts)",
      "Industry Specified Team of Expert Designers and Developers",
      "Upto 5 Custom designed Inner pages",
      "3 Premium Stock Photos",
      "3 Unique Custom Banner Design",
      "Up To 150 Products",
      "Up To 7 Categories",
      "Interactive jQuery Slider",
      "Cross platform (Desktop, iPhone, Android, etc) responsive compatibility",
      "Cross browser (Chrome, Firefox, Safari, etc) compatibility",
      "Conceptual And Dynamic Website",
      "Easy Product Search",
      "Product Reviews",
      "Search Engine Submission",
      "Full Shopping Cart Integration",
      "Payment Module Integration",
      "Google-Friendly Sitemap",
      "Complete W3C Certified HTML",
      "30 Days Free (Post-launch support)",
      "Unlimited Revisions",
      "Complete Deployment",
      "Dedicated Accounts Manager",
      "24/7 Customer Support",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
    ],
  },
  {
    id: 2,
    name: "Standard WEBSITE",
    price: "$799.00",
    list: [
      "Custom designed Homepage (2x concepts)",
      "Industry Specified Team of Expert Designers and Developers",
      "Upto 10 Custom designed Inner pages",
      "8 Premium Stock Photos",
      "5 Unique Custom Banner Design",
      "Up To 350 Products",
      "Up To 15 Categories",
      "Interactive jQuery Slider",
      "Cross platform (Desktop, iPhone, Android, etc) responsive compatibility",
      "Cross browser (Chrome, Firefox, Safari, etc) compatibility",
      "Conceptual And Dynamic Website",
      "Content Management System (CMS)",
      "Signup Area (For Newsletters, Offers etc.)",
      "Product sorting (Newest, Featured, Popular, Best Seller)",
      "Easy Product Search",
      "Product Reviews",
      "Search Engine Submission",
      "Full Shopping Cart Integration",
      "Payment Module Integration",
      "Sales & Inventory Management",
      "Google-Friendly Sitemap",
      "Complete W3C Certified HTML",
      "Social Media Integration (Facebook, Twitter, LinkedIn)",
      "Live Chat/Bot Chat Integration (Optional)",
      "30 Days Free (Post-launch support)",
      "Unlimited Revisions",
      "Complete Deployment",
      "Dedicated Accounts Manager",
      "24/7 Customer Support",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
    ],
  },
  {
    id: 3,
    name: "Enterprise WEBSITE",
    price: "$1,399.00",
    list: [
      "Custom designed Homepage (4x concepts)",
      "Industry Specified Team of Expert Designers and Developers",
      "Upto 10-15 Custom designed Inner pages",
      "Tailor-Made Design",
      "Professional, Modern, Unique Design",
      "15-20 Premium Stock Photos",
      "10 Unique Custom Banner Design",
      "Sliding Banner",
      "Up To 650 Products",
      "Unlimited Categories",
      "Product Summary Reports (Out Of Stock / Most Sold / Lowest Sale Etc)",
      "Product sorting (Newest, Featured, Popular, Best Seller)",
      "Multiple Product variation (Color, Size, Quantity, and other attributes)",
      "Product View With Multiple Views",
      "Multiple Filtrations Option",
      "Product Rating",
      "Product Detail With A Similar Product Range",
      "Product Detail With Similar Product Range Coupon Code Generation (By Category And Product)",
      "Cross platform (Desktop, iPhone, Android, etc) responsive compatibility",
      "Cross browser (Chrome, Firefox, Safari, etc) compatibility",
      "User-Friendly Navigation",
      "Search Engine Submission",
      "Content/Inventory Management System",
      "Products Showcase",
      "New Arrival Products Showcase",
      "Discount Coupons",
      "Payment Module Integration",
      "Multi-Currency Support (Optional)",
      "Shopping Cart Integration",
      "Direct Checkout",
      "Tax Calculator Integration",
      "Easy Product Search Bar",
      "Shipping Methods Integration",
      "Wishlist",
      "Live Chat/Bot Chat Integration",
      "Search Engine Submission",
      "SEO Friendly Content",
      "Blog Page (If Required)",
      "Social Media Integration (Facebook, Twitter, LinkedIn)",
      "Google-Friendly Sitemap",
      "Fast Load Time",
      "60 Days Free (Post-launch support)",
      "Unlimited Revisions",
      "Complete Deployment",
      "Complete Source Files",
      "Dedicated Project Manager",
      "24/7 Customer Support",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Unique Design Guarantee",
    ],
  },
];

export const customAppsPackagesData = [
  {
    id: 1,
    name: "CUSTOM WEBSITE",
    price: "$450.00",
    list: [
      "Best Value for Money Guaranteed!",
      "Customization work for you! Our social media experts.",
      "The custom social media packages can include any of the features of Gold and Platinum packages as well as paid social media advertising.",
    ],
  },
];

export const webPortalPackagesData = [
  {
    id: 1,
    name: "STARTUP WEBSITE",
    price: "$4000.00",
    list: [
      "Complete Custom Design & Development",
      "Dating Portal, Job Portal, Professional Network Portal, Social Network Portal, Enterprise Portal (Any One)",
      "Unique, User-Friendly, Interactive, Dynamic, High-End UI Design",
      "Unlimited Banner Designs",
      "Unlimited Stock Images",
      "User Signup Area",
      "Client/User Dashboard Area",
      "Custom Coding and Development",
      "Content Management System (Custom)",
      "Online Appointment/Scheduling/Online Ordering Integration (Optional)",
      "Online Payment Integration (Optional)",
      "Multi Lingual (Optional)",
      "Custom Dynamic Forms (Optional)",
      "Shopping Cart Integration (Optional)",
      "Web Traffic Analytics Integration",
      "Signup Area (For Newsletters, Offers etc.)",
      "Search Bar for Easy Search",
      "Live Feeds of Social Networks integration (Optional)",
      "Search Engine Submission",
      "Module-wise Architecture",
      "Extensive Admin Panel",
      "Award Winning Team of Expert Designers and Developers",
      "Complete Deployment",
      "Value Added Services",
      "Complete Source Files",
      "Dedicated Project Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Money Back Guarantee",
    ],
  },
  {
    id: 2,
    name: "WEB PORTAL PLUS",
    price: "$7000.00",
    list: [
      "Complete Custom Design & Development",
      "Dating Portal, Job Portal, Professional Network Portal, Social Network Portal, Restaurant Portal, Medical Portal, Enterprise Portal (Any One)",
      "Unique, User-Friendly, Interactive, Dynamic, High-End UI Design",
      "Unlimited Banner Designs",
      "Interactive Sliding Banners",
      "Special Hover Effects",
      "Unlimited Stock Images",
      "User Signup Area",
      "Client/User Dashboard Area",
      "Custom Coding and Development",
      "Content Management System (Custom)",
      "Online Appointment/Scheduling/Online Ordering Integration (Optional)",
      "Online Payment Integration (Optional)",
      "Multi-Lingual (Optional)",
      "Custom Dynamic Forms (Optional)",
      "Shopping Cart Integration (Optional)",
      "Complete Database Creation",
      "Signup Automated Email Authentication",
      "Web Traffic Analytics Integration",
      "3rd Party API Integrations",
      "Signup Area (For Newsletters, Offers, etc.)",
      "Search Bar for Easy Search",
      "Live Feeds of Social Networks integration (Optional)",
      "Search Engine Submission",
      "Module-wise Architecture",
      "Extensive Admin Panel",
      "Award Winning Team of Expert Designers and Developers",
      "Complete Deployment",
      "Value Added Services",
      "Complete Source Files",
      "Dedicated Project Manager",
      "100% Ownership Rights",
      "100% Satisfaction Guarantee",
      "100% Money Back Guarantee",
    ],
  },
];

export const seoPackagesData = [
  {
    id: 1,
    name: "BASIC",
    price: "$299.00",
    list: [
      "10 Keywords Optimization",
      "4 Keywords in top 10",
      "Search Engine Submissions",
      "2 Blogs Writing",
      "4 Blog Posting Links",
      "10 Blogs Social Bookmarking Links",
      "1 Press Release Writing",
      "2 Press Release Links",
    ],
  },
  {
    id: 2,
    name: "STANDARD",
    price: "$499.00",
    list: [
      "25 Keywords Optimization",
      "10 Keywords in Top 10",
      "Search Engine Submissions",
      "6 Blogs Writing",
      "12 Blog Posting Links",
      "20 Blogs Social Bookmarking Links",
      "2 Press Release Writing",
      "4 Press Release Links",
    ],
  },
  {
    id: 3,
    name: "PROFESSIONAL",
    price: "$799.00",
    list: [
      "50 Keywords Optimization",
      "20 Keywords in the Top 10",
      "14 Blogs Writing",
      "28 Blog Posting Links",
      "30 Blogs Social Bookmarking Links",
      "4 Press Release Writing",
      "8 Press Release Links",
      "4 Guest Blogging Links",
    ],
  },
];

export const smmPackagesData = [
  {
    id: 1,
    name: "BRONZE",
    price: "$397.00",
    list: [
      "Optimize FB Page",
      "1 Social Cover",
      "Engagement",
      "Reviews",
      "Check-ins",
      "Posts",
      "3 Posts per Week",
      "1 Facebook Event",
      "Monthly Reporting Ad",
    ],
  },
  {
    id: 2,
    name: "SILVER",
    price: "$597.00",
    list: [
      "Optimize FB Page",
      "1 Social Cover",
      "Engagement",
      "Reviews",
      "Check-ins",
      "Posts",
      "Shares",
      "Mentions",
      "Invite to Like",
      "Inbox Responses",
      "4 Posts per Week",
      "2 Facebook Events",
      "Monthly Reporting",
      "Ad Spend - Up to $65",
    ],
  },
  {
    id: 3,
    name: "GOLD",
    price: "$997.00",
    list: [
      "Optimize FB Page",
      "1 Social Cover",
      "Engagement",
      "Reviews",
      "Check-ins",
      "Posts",
      "Shares",
      "Mentions",
      "Invite to Like",
      "Inbox Responses",
      "5 Posts per Week",
      "2 Facebook Events",
      "1 Lead Generation Campaign",
      "Monthly Reporting",
      "Ad Spend - Up to $120",
    ],
  },
];
